#!/bin/bash

DATASET_LOCATION=rnn_features.csv
LEARNING_RATE=0.001
NUM_LAYERS=1
SKIP_CONNECTIONS=False
DROPOUT=0.5
HIDDEN_LAYERS=2
GRAD_CLIPPING=True
CELL_TYPE=lstm
HIDDEN_SIZE=128
BIDIRECTIONAL=True
EPOCHS=100
RESULTS_DIR=./results_feat_rnn/
BATCH_SIZE=10

~/anaconda3/bin/python3 features_rnn.py  $DATASET_LOCATION $RESULTS_DIR $BATCH_SIZE $LEARNING_RATE $NUM_LAYERS $SKIP_CONNECTIONS $DROPOUT $HIDDEN_LAYERS $GRAD_CLIPPING $CELL_TYPE $BIDIRECTIONAL $HIDDEN_SIZE $EPOCHS
