#!/bin/bash

DATASET_LOCATION=rnn_features.csv
LEARNING_RATE=0.0001
NUM_LAYERS=2
SKIP_CONNECTIONS=False
DROPOUT=0.5
HIDDEN_LAYERS=2
GRAD_CLIPPING=False
CELL_TYPE=lstm
HIDDEN_SIZE=128
BIDIRECTIONAL=True
EPOCHS=1
RESULTS_DIR=./f_results/
BATCH_SIZE=2

python3 features_rnn.py  $DATASET_LOCATION $RESULTS_DIR $BATCH_SIZE $LEARNING_RATE $NUM_LAYERS $SKIP_CONNECTIONS $DROPOUT $HIDDEN_LAYERS $GRAD_CLIPPING $CELL_TYPE $BIDIRECTIONAL $HIDDEN_SIZE $EPOCHS